In [1]:
import numpy as np
twoDarray = np.array([[1,2,3],[4,5,6]])
for i in twoDarray:
    print(i)


[1 2 3]
[4 5 6]


In [3]:
for i in twoDarray:
    for j in i:
        print(j)

1
2
3
4
5
6


In [6]:
threeDarray = np.array([[[1,2,3,],[-4,-5,6],[7,8,9],[-7,-8,-9]]])
for i in threeDarray:
    print(i)

[[ 1  2  3]
 [-4 -5  6]
 [ 7  8  9]
 [-7 -8 -9]]


In [8]:
threeDarray = np.array([[[1,2,3,],[-4,-5,6],[7,8,9],[-7,-8,-9]]])
for i in threeDarray:
    for j in i:
        print(j)
    

[1 2 3]
[-4 -5  6]
[7 8 9]
[-7 -8 -9]


In [ ]:
threeDarray = np.array([[[1,2,3,],[-4,-5,6],[7,8,9],[-7,-8,-9]]])
for i in threeDarray:
    for j in i:
        for j in k:
            print(k)
         