In [2]:
import numpy as np
twoDarray = np.array([[1,2,3],[4,5,6]])
print(twoDarray[1])

[4 5 6]


In [3]:
print(twoDarray[1,0])

4


In [4]:
threeDarray = np.array([[[1,2,3,],[-4,-5,6],[7,8,9]]])
print(threeDarray)

[[[ 1  2  3]
  [-4 -5  6]
  [ 7  8  9]]]


In [6]:
print(threeDarray[0,1])

[-4 -5  6]


In [7]:
print(threeDarray[0,1,0])

-4


In [8]:
print(threeDarray[0,1,1])

-5


In [9]:
print(threeDarray[0,2,1])

8


In [14]:
print(threeDarray[0,1,2])

6
