In [1]:
pip install pandas numpy matplotlib seaborn


Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Packages installed successfully!")



Matplotlib is building the font cache; this may take a moment.


Packages installed successfully!


In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Packages installed successfully!")


Packages installed successfully!


In [7]:
import numpy as np
oneDarray = np.array([1,2,3,4,5,])
print(oneDarray)

[1 2 3 4 5]


In [8]:
print(oneDarray.ndim)

1


In [13]:
twoDarray = np.array([[1,2,3],[5,6,7]])
print(twoDarray)

[[1 2 3]
 [5 6 7]]


In [14]:
print(twoDarray.ndim)

2


In [15]:
threeDarray = np.array([[[1,2,3],[5,6,7],[-5,-6,-7]]])
print(threeDarray)

[[[ 1  2  3]
  [ 5  6  7]
  [-5 -6 -7]]]


In [16]:
print(threeDarray.ndim)

3


In [17]:
import os
print(os.getcwd())


C:\Users\HUBERT
